name: CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"

jobs:
  typescript:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, ':bookmark:')"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 20
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint
        run: npx oxlint src && npx oxfmt --check .

  rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
          - platform: windows-latest

    runs-on: ${{ matrix.platform }}
    if: "!startsWith(github.event.head_commit.message, ':bookmark:')"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable

      - name: Rust cache
        uses: swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Cargo check
        run: cargo check --manifest-path src-tauri/Cargo.toml

      - name: Cargo clippy
        run: cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings

      - name: Cargo test
        run: cargo test --manifest-path src-tauri/Cargo.toml
